### ISSUE TITLE
KeyError in shepherd.py

### ISSUE THREAD

**Issue by jakpra** [XiangLi1999/PosteriorControl-NLG#1]
I'm getting this error whenever running shepherd.py:

```
Traceback (most recent call last):
  File "shepherd.py", line 615, in <module>
    imp.load_source('modulename', EXP_FILE).__dict__[task]()
  File "/home/jakob/PosteriorControl-NLG/shepherd.py", line 183, in decorated
    for bfr in before: bfr()
  File "/home/jakob/PosteriorControl-NLG/shepherd.py", line 275, in init
    if SYS.host == 'local' or _args.local:
  File "/home/jakob/PosteriorControl-NLG/shepherd.py", line 62, in __getattr__
    return self.__getitem__(key)
  File "/home/jakob/PosteriorControl-NLG/shepherd.py", line 56, in __getitem__
    return VarDict._getattr_(self, key)
  File "/home/jakob/PosteriorControl-NLG/shepherd.py", line 44, in _getattr_
    return obj.my_dict[key]
KeyError: 'host'
```
Am I correct in assuming that SYS.host should be set somewhere in setup()?

**Comment by jakpra** [comment]
Nevermind, I realized shepherd needs the `.spdrc.json` config, which solves the error. It would be great if you could add this file (or a pointer to it) to the repo/readme.

I really like your paper by the way, so I'm looking forward to playing around with the code & models!
